#!/bin/bash -o data/Multi_Domain_Sentiment_Dataset/json_files;
mkdir data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/apparel/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/automotive/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/baby/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/beauty/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/books/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/camera_\&_photo/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/cell_phones_\&_service/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/computer_\&_video_games/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/dvd/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/electronics/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/gourmet_food/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/grocery/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/health_\&_personal_care/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/jewelry_\&_watches/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/kitchen_\&_housewares/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/magazines/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/music/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/musical_instruments/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/office_products/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/outdoor_living/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/software/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/sports_\&_outdoors/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/tools_\&_hardware/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/toys_\&_games/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
python src/mdsd2json.py data/Multi_Domain_Sentiment_Dataset/sorted_data/video/all.review -o data/Multi_Domain_Sentiment_Dataset/json_files;
